spring:
  application:
    name: ofisy-notifications
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

app:
  aws:
    sqs:
      notification-queue: techchallenge-ofisy-notifications-queue.fifo
    dynamodb:
      table-name: Notifications